const router = require('express').Router();
const db = require('../config/database');
const mysql = require('mysql2/promise');
const fs = require('fs');
const path = require('path');
const SRP6 = require('../services/srp6');

/* GET /install */
router.get('/', (req, res) => {
  if (db.isInstalled()) {
    return res.redirect('/');
  }
  res.render('pages/install/index', {
    title: 'Installation Wizard',
    layout: false,
    step: parseInt(req.query.step) || 1,
    error: null,
    success: null
  });
});

/* POST /install/test-db — Test database connection */
router.post('/test-db', async (req, res) => {
  const { host, port, user, password, database: dbName } = req.body;
  try {
    const conn = await mysql.createConnection({
      host, port: parseInt(port || '3306'),
      user, password: password || '',
      database: dbName,
      connectTimeout: 5000
    });
    await conn.query('SELECT 1');
    await conn.end();
    res.json({ success: true, message: 'Connection successful!' });
  } catch (err) {
    res.json({ success: false, message: err.message });
  }
});

/* POST /install/run — Execute installation */
router.post('/run', async (req, res) => {
  try {
    const {
      cms_host, cms_port, cms_user, cms_pass, cms_db,
      auth_host, auth_port, auth_user, auth_pass, auth_db,
      char_host, char_port, char_user, char_pass, char_db,
      world_host, world_port, world_user, world_pass, world_db,
      site_title, admin_user, admin_pass, admin_email,
      soap_host, soap_port, soap_user, soap_pass
    } = req.body;

    // 1. Connect to CMS database
    const conn = await mysql.createConnection({
      host: cms_host, port: parseInt(cms_port || '3306'),
      user: cms_user, password: cms_pass || '',
      database: cms_db, multipleStatements: true
    });

    // 2. Run SQL schema
    const sqlFile = path.join(__dirname, '../../sql/full_install.sql');
    const sql = fs.readFileSync(sqlFile, 'utf8');
    await conn.query(sql);

    // 3. Update site config
    if (site_title) {
      await conn.query(
        "UPDATE mw_config SET `value` = ? WHERE `key` = 'site_title'",
        [site_title]
      );
    }
    if (admin_email) {
      await conn.query(
        "UPDATE mw_config SET `value` = ? WHERE `key` = 'site_email'",
        [admin_email]
      );
    }

    // 4. Create admin account in auth DB
    const authConn = await mysql.createConnection({
      host: auth_host, port: parseInt(auth_port || '3306'),
      user: auth_user, password: auth_pass || '',
      database: auth_db
    });

    // Check if admin account exists
    const [existing] = await authConn.query(
      'SELECT id FROM account WHERE username = ?',
      [admin_user.toUpperCase()]
    );

    let adminId;
    if (existing.length) {
      adminId = existing[0].id;
    } else {
      // Create admin account with SRP6
      const { salt, verifier } = SRP6.generateCredentials(admin_user, admin_pass);
      const [result] = await authConn.query(
        'INSERT INTO account (username, salt, verifier, email, reg_mail, expansion) VALUES (?, ?, ?, ?, ?, 2)',
        [admin_user.toUpperCase(), salt, verifier, admin_email, admin_email]
      );
      adminId = result.insertId;
    }

    await authConn.end();

    // 5. Create CMS admin record
    await conn.query(
      `INSERT INTO mw_account_extend (account_id, account_level, activation_code, registration_ip)
       VALUES (?, 4, '', '127.0.0.1')
       ON DUPLICATE KEY UPDATE account_level = 4`,
      [adminId]
    );

    // 6. Insert default realm config
    const [realms] = await mysql.createConnection({
      host: auth_host, port: parseInt(auth_port || '3306'),
      user: auth_user, password: auth_pass || '',
      database: auth_db
    }).then(async c => { const r = await c.query('SELECT id FROM realmlist LIMIT 1'); await c.end(); return r; });

    if (realms.length) {
      await conn.query(
        `INSERT IGNORE INTO mw_realm (realm_id, site_enabled, db_char_host, db_char_port, db_char_name,
         db_char_user, db_char_pass, db_world_host, db_world_port, db_world_name,
         db_world_user, db_world_pass, ra_type, ra_port, ra_user, ra_pass)
         VALUES (?, 1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?, ?)`,
        [realms[0].id,
         char_host, char_port || '3306', char_db, char_user, char_pass || '',
         world_host, world_port || '3306', world_db, world_user, world_pass || '',
         parseInt(soap_port || '7878'), soap_user || '', soap_pass || '']
      );
    }

    await conn.end();

    // 7. Write .env file
    const envContent = `# MaNGOSWebV5 - Generated by installer
PORT=${process.env.PORT || 3000}
HOST=${process.env.HOST || 'localhost'}
BASE_URL=${process.env.BASE_URL || 'http://localhost:3000'}

SESSION_SECRET=${require('crypto').randomBytes(32).toString('hex')}
SESSION_LIFETIME=2592000000

CMS_DB_HOST=${cms_host}
CMS_DB_PORT=${cms_port || 3306}
CMS_DB_USER=${cms_user}
CMS_DB_PASS=${cms_pass || ''}
CMS_DB_NAME=${cms_db}

AUTH_DB_HOST=${auth_host}
AUTH_DB_PORT=${auth_port || 3306}
AUTH_DB_USER=${auth_user}
AUTH_DB_PASS=${auth_pass || ''}
AUTH_DB_NAME=${auth_db}

CHAR_DB_HOST=${char_host}
CHAR_DB_PORT=${char_port || 3306}
CHAR_DB_USER=${char_user}
CHAR_DB_PASS=${char_pass || ''}
CHAR_DB_NAME=${char_db}

WORLD_DB_HOST=${world_host}
WORLD_DB_PORT=${world_port || 3306}
WORLD_DB_USER=${world_user}
WORLD_DB_PASS=${world_pass || ''}
WORLD_DB_NAME=${world_db}

SOAP_HOST=${soap_host || '127.0.0.1'}
SOAP_PORT=${soap_port || 7878}
SOAP_USER=${soap_user || 'admin'}
SOAP_PASS=${soap_pass || 'admin'}

SMTP_ENABLED=false
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_SECURE=tls
SMTP_USER=
SMTP_PASS=
MAIL_FROM_EMAIL=noreply@example.com
MAIL_FROM_NAME=MaNGOSWebV5

RECAPTCHA_ENABLED=false
RECAPTCHA_SITE_KEY=
RECAPTCHA_SECRET_KEY=

PAYPAL_EMAIL=
PAYPAL_SANDBOX=true
`;
    fs.writeFileSync(path.join(__dirname, '../../.env'), envContent);

    // Reload env
    require('dotenv').config({ path: path.join(__dirname, '../../.env'), override: true });

    // Re-init database pools
    await db.reinit();

    res.json({
      success: true,
      message: 'Installation complete! The server will now restart. Please refresh the page.'
    });

  } catch (err) {
    res.json({ success: false, message: err.message });
  }
});

module.exports = router;
